# Generated by Django 6.1 on 2026-09-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_expense_options_expense_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
